### ISSUE TITLE
Overall feedback

### ISSUE THREAD

**Issue by rglassett** [brandonlilly/LastAirBnb#1]
Love the theme! Last Airbender has a lot of great visuals and will make your listings stand out.

The map is immensely important. It's a central part of most AirBNB projects, and for good reason: it's very flashy, adds some good user interaction, and shows mastery of an outside API. Make it a core feature and consider building some other features around it (geocoding is a good one).

A note on the order of things: searching listings is much more important than creating listings. Your audience will be searching much, much more often than they will be trying to post content. Adjust your schedule accordingly.

Schema stuff:
Sessions table will need a `session_token` column
`listings.address` should not be an integer; probably a string, instead.
`amenities.name` should probably be unique

**Comment by brandonlilly** [comment]
Thanks for the feedback. I'll make sure to get the map done as a core feature. I only put creating a listing as high up as it was because I figured I'd be using my own form. I should probably just put everything in the seed file though. Those were some pretty silly database typos- will fix.
